sudo: required

services:
  - docker

jobs:
  include:
    - stage: python3.6
      script:
        - cd 3.6
        - docker build -t python36-nodejs .
        - docker run python36-nodejs /bin/sh -c "python3.6 -V && pip --version && pipenv --version && node -v && npm -v && yarn --version"

    - stage: python3.7
      script:
        - cd 3.7
        - docker build -t python37-nodejs .
        - docker run python37-nodejs /bin/sh -c "python3.7 -V && pip --version && pipenv --version && node -v && npm -v && yarn --version"
